#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the shell interpreter.
#
#       For example: 'sh gradle' with ksh (checked on ksh)
#
#   (2) This script points to the Java runtime (JRE) and classpath. It uses the
#       environment variables JAVA_HOME and GRADLE_OPTS.
#
#       Setting the JRE location: Usually either $JAVA_HOME (JDK install) or
#       $JAVA_HOME/jre (JRE install) has the 'java' executable.
#
#       Setting the classpath: Use GRADLE_OPTS to pass the classpath
#       (e.g. GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx4g -cp /path/to/classpath")
#       or add additional classpath directories to the "APP_CLASSPATH" array.
#
#       Gradle distribution: The common structure for a distribution is:
#        - gradle-core (runtime engine)
#        - gradle-wrapper (the wrapper bootstrapper and its configuration)
#        - gradle-wrapper.jar (JAR file)
#        - gradle/wrapper/gradle-wrapper.jar (distribution JAR)
#        - gradle/wrapper/gradle-wrapper.properties (wrapper properties)
#
#       The gradle/wrapper/gradle-wrapper.properties is the configuration for
#       this script and the gradlew script (Unix) and gradlew.bat (Windows).
#
#       To use a specific distribution (instead of what is in gradle-wrapper.properties),
#       you can set the environment variable "DISTRIBUTION_URL".
#
#   Happy Gradling!
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined for 'unlimited' and 'max'
        # In POSIX sh, using "unlimited" inside a case statement fails on Debian
        # So we default to 'max' for the maximum here.
        MAX_FD=$(ulimit -n)
        if [ $? -ne 0 ] ; then
            warn "Could not query maximum file descriptor limit"
            MAX_FD=
        fi
        ;;
      esac
    if test "x$MAX_FD" != "x" ; then
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit to $MAX_FD"
        fi
    fi
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module module-path is given)
#   * --module (only if dedicated module is given)
#   * Together with ARTIFACTORY_CLI_JAVA_OPTS, but GRADLE_OPTS and ARTIFACTORY_CLI_JAVA_OPTS are at the start
#     to support daemon (and Gradle) stop ports.
#   * At the very end, the main class,
#   * then the single application arguments

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - we need a fake cygwin style function (with --)
    # For most of the arguments, the simple conversion works. Let's convert some specific ones: --module-path, --module
    # The --module-path tries to convert paths so use cygpath on them, but leave the option.
    # The --module does not take a value, so nothing to convert.
    # For all other options (both standard and main class), just pass them through.
    while [ $# -gt 0 ]; do
        case "$1" in
            --module-path)
                module_path="$2"
                shift 2
                module_path=$(cygpath --path --mixed "$module_path")
                set -- "--module-path=$module_path" "$@"
                ;;
            --module)
                module="$2"
                shift 2
                set -- "--module=$module" "$@"
                ;;
            --)
                shift
                set -- "$@"
                break
                ;;
            *)
                set -- "$@" "$1"
                shift
                ;;
        esac
    done

    # Split APP_CLASSPATH into an array to allow use of spaces in paths
    IFS=" " read -r -a APP_CLASSPATH_ARRAY <<< "$APP_CLASSPATH"
    for part in "${APP_CLASSPATH_ARRAY[@]}"; do
        CLASSPATH="${CLASSPATH}:$(cygpath --path --mixed "$part")"
    done
    CLASSPATH=${CLASSPATH#?}
fi

# Determine if Gradle's daemon is enabled. If GLOBAL_DAEMON_CONTROL_GRADLE_OPTS is set,
# we'll use it for global control of the Gradle Daemon.
# See: https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:daemon_control_with_command_line
global_daemon_opts=${GLOBAL_DAEMON_CONTROL_GRADLE_OPTS:-}
if [ -n "$global_daemon_opts" ] ; then
    # Check for pre-existing --daemon or --no-daemon arguments to avoid overlapping.
    daemon_was_set=false
    for opt in $global_daemon_opts; do
        case "$opt" in
            --daemon | --no-daemon)
                daemon_was_set=true
                break
                ;;
        esac
    done
    if ! "$daemon_was_set" ; then
        # Add --daemon if GLOBAL_DAEMON_CONTROL_GRADLE_OPTS is set, assuming we want daemon.
        global_daemon_opts="$global_daemon_opts --daemon"
    fi
    # Remove leading and trailing whitespace.
    global_daemon_opts=$(echo "$global_daemon_opts" | xargs)
fi

# For Gradle Client, we first collect all arguments into a single string ARG_STR
# (this makes the invocation simpler), and then we split it using bash's array functionality.
# This approach isolates the problem of spaces in arguments (e.g., directories with spaces).
#
# We also forward the global daemon flags at the beginning of the ARG_STR.
if [ -n "$global_daemon_opts" ]; then
    ARG_STR="$global_daemon_opts"
else
    ARG_STR=""
fi

# Collect all arguments (except the global daemon-specific ones that we've already handled) into ARG_STR.
while [ $# -gt 0 ]; do
    case "$1" in
        --daemon | --no-daemon)
        # Already handled above, or will be handled by the daemon wrapper.
        shift
        ;;
        *)
        ARG_STR="$ARG_STR $1"
        shift
        ;;
    esac
done

# Append the main class to the arguments, as it's the first element of APP_ARGS.
APP_ARGS="${*}"
ARG_STR="$ARG_STR $APP_ARGS"

# Add the application class name (APP_CLASSNAME) to ARG_STR if we can.
# Typically, it is at the beginning.
if [ -n "$APP_CLASSNAME" ]; then
    ARG_STR="$APP_CLASSNAME $ARG_STR"
fi

# Now we replace all internal newlines spaces and tabs with simple spaces.
# This ensures we don't have to worry about internal spaces affecting argument split.
ARG_STR=$(printf %s "$ARG_STR" | tr '\n' ' ' | tr -s ' ' | sed 's/^ //' | sed 's/ $//')

# Split the arguments string into an array to allow the use of spaces inside arguments.
# It's important to use the default field separator.
IFS=" " read -r -a APP_ARGS_ARRAY <<< "$ARG_STR"

# Run the Java command.
# The shebang line above ensures a POSIX shell.
exec "$JAVACMD" \
     ${GRADLE_OPTS:-} \
     ${ARTIFACTORY_CLI_JAVA_OPTS:-} \
     -classpath "$CLASSPATH" \
     org.gradle.wrapper.GradleWrapperMain \
     "${APP_ARGS_ARRAY[@]}"